# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yoko's portfolio
email: gyang2@wpi.edu
description: >- # this means to ignore newlines until "baseurl:"
This website is created by Yoko to document all of Yoko's projects.
This site is one of the projects.
Yoko is a multilingual computer science major in the class of 2023 at Worcester Polytechnic Institute (WPI) in Massachusetts. He is passionate about software development and looks forward to having the software he develops used in meaningful ways in the real world. He is especially interested in projects that can improve people’s lives.
In his two and half years at WPI, Yoko worked with classmates on developing an application that allows users to submit requests to a hospital and then navigates them spatially within the hospital 
setting. 
Yoko has particular facility with Java, Javafx and C++ in implementing algorithms and in front end design.Born in Shanghai, Yoko is a native speaker of Mandarin and Shanghainese. He is also highly proficient in Japanese. 
Before coming to WPI, he studied and worked in Japan for four years, where he not only built up Japanese proficiency, but also gained knowledge and experience in psychology, management and social welfare. Yoko’s multicultural and cross-disciplinary background provides insight and informs him as he designs user-friendly software.
Yoko is available for full-time internships from 5/4/2022-7/24/2022.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: guang-yang-aa8a3422b
github_username:  Yoko-Guang-Yang

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
# 
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
